# Generated by Django 5.2.9 on 2025-12-03 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APICredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=100)),
                ("client_code", models.CharField(max_length=50)),
                ("secret_key", models.CharField(max_length=100)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("feed_token", models.TextField(blank=True, null=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StrategySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("start_time", models.TimeField(default="09:15:00")),
                ("end_time", models.TimeField(default="15:15:00")),
                ("max_total_trades", models.IntegerField(default=5)),
                (
                    "per_trade_sl_amount",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                ("pnl_exit_enabled", models.BooleanField(default=False)),
                (
                    "profit_target_amount",
                    models.DecimalField(
                        decimal_places=2, default=2000.0, max_digits=10
                    ),
                ),
                (
                    "stop_loss_amount",
                    models.DecimalField(
                        decimal_places=2, default=1000.0, max_digits=10
                    ),
                ),
                (
                    "volume_price_threshold",
                    models.DecimalField(
                        decimal_places=2, default=1000000.0, max_digits=15
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("token", models.CharField(max_length=50)),
                ("candle_ts", models.DateTimeField(blank=True, null=True)),
                (
                    "candle_open",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "candle_high",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "candle_low",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "candle_close",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "prev_day_high",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("entry_level", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stop_level", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target_level", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField(default=0)),
                ("transaction_type", models.CharField(default="BUY", max_length=10)),
                (
                    "entry_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "exit_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Monitor"),
                            ("PENDING_ENTRY", "Pending Entry Order"),
                            ("OPEN", "Open Position"),
                            ("PENDING_EXIT", "Pending Exit Order"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired (No Entry)"),
                            ("FAILED_ENTRY", "Entry Failed"),
                            ("FAILED_EXIT", "Exit Failed"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "exit_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
