# Generated by Django 5.2.9 on 2025-12-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tradeapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apicredential",
            name="secret_key",
        ),
        migrations.AddField(
            model_name="apicredential",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apicredential",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Monitor"),
                    ("PENDING_ENTRY", "Pending Entry Order"),
                    ("OPEN", "Open Position"),
                    ("PENDING_EXIT", "Pending Exit Order"),
                    ("CLOSED", "Closed"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                    ("FAILED_ENTRY", "Entry Failed"),
                    ("FAILED_EXIT", "Exit Failed"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
